#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop and disable the service
        systemctl stop keko-ts3bot 2>/dev/null || true
        systemctl disable keko-ts3bot 2>/dev/null || true
        ;;
esac

#DEBHELPER#

exit 0
